#!/usr/bin/bash

trap 'kill $server_pid; exit' INT

$BROWSER --app="http://localhost:5791"

# serve files
python -m http.server 5791 &
server_pid=$!

# have quarto compile to html
cd doc
quarto preview --no-serve --no-browser
